name: Build binaries and Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install -y nodejs
          sudo apt install -y binutils
          sudo apt install -y zip
          sudo apt install -y qt5-default
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Install npm dependencies
        run: |
          npm install
      - name: Initialize nodegui-packer
        run: |
          npx nodegui-packer --init revanced-builder
      - name: Build revanced-builder (webpack)
        run: |
          npm run build
      - name: Build
        run: |
          npx nodegui-packer --pack dist/
      - name: Zip release
        run: |
          cd deploy/linux/build/revanced-builder
          rm ./Application-x86_64.AppImage
          echo "./qode dist/" > "Run ReVanced-Builder.sh"
          cd ..
          zip -r revanced-builder-linux-x86_64.zip revanced-builder
      - name: Upload to Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            deploy/linux/build/revanced-builder-linux-x86_64.zip
          tag_name: ${{ env.RELEASE_VERSION }}
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Install npm dependencies
        run: |
          npm install
      - name: Initialize nodegui-packer
        run: |
          npx nodegui-packer --init revanced-builder
      - name: Build revanced-builder (webpack)
        run: |
          npm run build
      - name: Build
        run: |
          npx nodegui-packer --pack dist/
      - name: Zip release
        run: |
          cd deploy/win32/build
          Compress-Archive revanced-builder revanced-builder-windows.zip
      - name: Upload to Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            deploy/win32/build/revanced-builder-windows.zip
          tag_name: ${{ env.RELEASE_VERSION }}
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Install npm dependencies
        run: |
          npm install
      - name: Initialize nodegui-packer
        run: |
          npx nodegui-packer --init revanced-builder
      - name: Build revanced-builder (webpack)
        run: |
          npm run build
      - name: Build
        run: |
          npx nodegui-packer --pack dist/
      - name: Zip release
        run: |
          cd deploy/darwin/build
          zip -r revanced-builder-macos.zip ./
      - name: Upload to Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            deploy/darwin/build/revanced-builder-macos.zip
          tag_name: ${{ env.RELEASE_VERSION }}
